<div class="container">       
<div class="card text-white col-md-8 px-0">
    <div class="card-header bg-dark">ADD User</div>
    <div class="card-body">
        <?php if ($error !=''):?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
        <?php endif;?>
    <form method="POST">
        <div class="form-group">
            <label class="text-secondary" for="username">Username</label>
            <input type="text"  class="form-control" id="username" name="username" value="<?=$username?>">
        </div> 

        <div class="form-group">
            <label class="text-secondary" for="email">email</label>
            <input type="email"  class="form-control" id="email" name="email"  value="<?=$email?>">
        </div>

        <div class="form-group">
            <label class="text-secondary" for="password">password</label>
            <input type="password"  class="form-control" id="password" name="password">
        </div> 

        <div class="form-group">
            <label class="text-secondary" for="confirmation">password confirmation</label>
            <input type="password"  class="form-control" id="confirmation" name="confirmation">
        </div>

            <div class="form-group">
            <label class="text-secondary" for="firstname">first name</label>
            <input type="text"  class="form-control" id="firstname" name="firstname" value="<?=$firstName?>">
        </div> 

            <div class="form-group">
            <label class="text-secondary" for="lastname">last name</label>
            <input type="text"  class="form-control" id="lastname" name="lastname"  value="<?=$lastName?>">
        </div> 

        <div class="form-group text-secondary">description</label>
            <textarea class="form-control" id="bio" name="bio" rows="3" value="<?=$bio?>"></textarea>
        </div>

        <div class="form-group  text-secondary">Role</label>
            <select name="role" id="role value=<?$role?>">
                    <option value="role_admin">Admin</option>
                    <option value="role_autor">autor</option>
            </select>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Enregistrer</button>
            </div>
        </div>
        
    </form>
    </div>
</div>
</div>  
