<div class="container">
    <h1>Accueil</h1>
    <div class="row">
    <div class="col-md-4">

    <div class="card text-white mb-3">
        <div class="card-header bg-dark">Visualisation rapide</div>
        <div class="card-body">
        <p class="text-body">Pour voir tout de suite votre site</p>
        <a class="d-block btn btn-primary" href="#">Afficher votre site</a>
        </div>
    </div>

    <div class="card text-white">
            <div class="card-header bg-dark">Actions rapides </div>
            <div class="card-body">
            <a class="d-block card-link ml-4" href="#"><i class="far fa-newspaper" aria-hidden="true"></i>Ajouter un article</a>  
            <a class="d-block card-link" href="#"><i class="far fa-file"aria-hidden="true"></i>Ajouter une page</a>
            <a class="d-block card-link" href="#"><i class="fas fa-user-alt" aria-hidden="true"></i>Ajouter un utilisateur</a>
            </div>  
        </div>
        </div> 
    
    <div class="card text-white col-md-8 px-0">
        <div class="card-header bg-dark">Article rapides </div>
            <div class="card-body">
            <form>
                <div class="form-group">
                    <label class="text-body">Titre de l'article</label>
                    <input class="form-control form-control-lg" type="text" placeholder="Titre">
                </div> 
                <div class="form-group">
                    <label class="text-body">Texte de l'article</label>
                    <textarea class="form-control" rows="3"></textarea>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="option1" checked>
                    <label class="form-check-label text-body mr-4" for="gridRadios1">
                        Publier
                    </label>
                    <input class="form-check-input " type="radio" name="gridRadios" id="gridRadios1" value="option1" checked>
                    <label class="form-check-label text-body" for="gridRadios1">
                        Brouillon
                    </label>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </div>
                    </div>
                </form>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-7">
            <ul class="list-group">
                <li class="list-group-item active bg-dark mt-5">
                    <h4>Liste des derniers articles</h4>
                </li>
                <li class="list-group-item">
                    <h6>Article 1</h6>
                    <p>début du texte de l'article(...)</p>
                </li>
                <li class="list-group-item">
                    <h6>Article 2</h6>
                    <p><p>début du texte de l'article(...)</p>
                </li>
                <li class="list-group-item">
                    <h6>Article 3</h6>
                    <p><p>début du texte de l'article(...)</p>
                </li>
                <li class="list-group-item">
                    <h6>Article 4</h6>
                    <p><p>début du texte de l'article(...)</p>
                </li>
            </ul>
            <a href="#">Voir tout les articles</a>
        </div>

    <div class="col-12 col-md-5">
        <ul class="list-group">
        <li class="list-group-item active bg-dark mt-5"">
            <h4>Liste des derniers articles</h4>
        </li>
        <li class="list-group-item">
            <p class="font-weight-bold"> Lorem ipsum dolor sit amet, consectetur(...)</p>
        </li>
        <li class="list-group-item">
            <p class="font-weight-bold"> Lorem ipsum dolor sit amet, consectetur(...)</p>
        </li>
        <li class="list-group-item">
            <p class="font-weight-bold"> Lorem ipsum dolor sit amet, consectetur(...)</p>
        </li>
        <li class="list-group-item">
            <p class="font-weight-bold"> Lorem ipsum dolor sit amet, consectetur(...)</p>
            </li>
            </ul>
            <a href="#">Voir tout les articles</a>
    </div>
    </div>
    </div>

