<div class="container">       
    <div class="card text-white col-md-8 px-0">
        <div class="card-header bg-dark">login</div>
        <div class="card-body">
        <?php if ($error !=''):?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
        <?php endif;?>
        <form method="POST" action="login.php" >
            <div class="form-group">
                <label class="text-secondary" for="email">email</label>
                <input type="email"  class="form-control" id="email" name="email">
            </div> 

            <div class="form-group">
                <label class="text-secondary" for="password">password</label>
                <input type="password"  class="form-control" id="password" name="password">
            </div>
            <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">submit</button>
            </div>
        </div>
        </form>
        </div>
        </div>

